mysql:
  host: 127.0.0.1
  port: 3306
  database: douyin
  username: root
  password: admin123
redis:
  address: 127.0.0.1
  network: tcp
  port: 6379
  auth:
minio:
  host: 172.20.10.8
  port: 9001
  accessKeyID: admin123
  secretAccessKey: admin123
  videobuckets: video
  picbuckets: pic

videofile: /Users/didi/simple-demo/file/video/
logfile: /Users/didi/simple-demo/file/log/
picfile: /Users/didi/simple-demo/file/pic/
level: info